# This is a basic workflow to help you get started with Actions

name: SPFX CI CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ beta ]

env:
  packageName: test-list-items.sppkg
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 10.x
          
      - name: NPM Install
        run: npm install
        
      - name: Gulp build
        run: gulp build
         
      - name: npm test
        run: npm test
        
      - name: gulp bundle
        run: gulp bundle --ship
        
      - name: package solution
        run: gulp package-solution --ship
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: packageFile
          # A file, directory or wildcard pattern that describes what to upload
          path: sharepoint/solution/${{ env.packageName }}
        
  deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: [build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        # Artifact name
        name: packageFile
        
    - name: PnP PowerShell Deploy App
      # You may pin to the exact commit or the version.
      # uses: aakashbhardwaj619/action-pnp-powershell-deploy@1914c8cc93afbef90b3aeb44e1369849835f0ca4
      uses: aakashbhardwaj619/action-pnp-powershell-deploy@v1.0.0
      with:
        # URL of the SharePoint Site
        SHAREPOINT_SITE_URL: https://in8aakbh.sharepoint.com/sites/UHSD1
        # Username of the admin
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        # Password of the admin
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        # Relative path of the app in your repo
        APP_FILE_PATH: ${{ env.packageName }}
        # True or false. Set to overwrite the existing package file. Default is false
        OVERWRITE: true
        # Scope of the app catalog: Tenant|Site. Default is Tenant
        SCOPE: Site
